version: "3.8"  # Specify the Docker Compose version

services:
  backend:
    build: ./ # Path to your backend Dockerfile
    ports:
      - "8080:8080"  # Expose port 8080 of the container to port 8080 on your host
    environment:
      # Add environment variables for Redis connection details (if applicable)
      REDIS_HOST: redis  # Assuming Redis service name is "redis"

#  frontend:
#    build: ./frontend  # Path to your frontend Dockerfile
#    ports:
#      - "3000:3000"  # Expose port 3000 of the container to port 3000 on your host
#    depends_on:
#      - backend  # Start the frontend service only after the backend is up

  redis:
    image: redis:7.2.4  # Use a specific version if needed
    ports:
      - "6379:6379"